# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
java_version=17

# Project
mod_version=0.0.0-dev
release_type=beta

# Common
mc_version=1.20.1

# Forge
forge_version=47.1.3

# Fabric
fabric_api_version=0.84.0+1.20.1
fabric_loader_version=0.14.21

# Mod options
mod_name=Origins Compat
mod_author=possible_triangle
mod_id=origins_compat
maven_group=com.possible-triangle

# Dependencies
mixin_extras_version=0.4.1
caelus_version=3.2.0+1.20.1
pehkui_version=3.8.2
calio_forge_version=5404005
apoli_forge_version=5404008
jei_version=15.20.0.106
appleskin_version=XdXDExVF

flywheel_version=1.0.1
origins_forge_version=5314209
registrate_forge_version=MC1.20-1.3.3
ponder_forge_version=1.0.43
create_forge_version=6.0.2-52
farmers_delight_version=1.20.1-1.2.4

registrate_fabric_version=1.3.69-MC1.20.1
create_fabric_version=6.0.0.0+mc1.20.1-build.1653
origins_fabric_version=v1.7.1
apoli_fabric_version=2.11.11
calio_fabric_version=v1.13.3
cca_version=5.3.0

# Releases
curseforge_project_id=711560
modrinth_project_id=xtXAknNA
repository=pssbletrngle/originscompat
