modLoader = "javafml"
loaderVersion = "[43,)"
license = 'LGPL'

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = ''''''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "origins"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
mandatory = false
versionRange = "[0.5.1.a,)"
ordering = "NONE"
side = "BOTH"