name: Build & Release
on:
  release:
    types: [ created ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Update mod version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'gradle.properties'
          property: 'version'
          value: ${{ github.event.release.tag_name }}

      - name: Build and upload
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build curseforge modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          CHANGELOG: ${{ github.event.release.body }}

      - name: Upload to GitHub release
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/origins_compat-${{ github.event.release.tag_name }}.jar
          asset_name: origins_compat-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive